package com.naveed.library_managment;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aghanaveed_
 */
public class Borrow_Book extends javax.swing.JInternalFrame {

    /**
     * Creates new form Borrow_Book
     */
    public Borrow_Book() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Category_Box = new javax.swing.JComboBox<>();
        Search_Field = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BorrowBook_Table = new javax.swing.JTable();
        BorrowBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(null);
        setAutoscrolls(true);
        setFrameIcon(null);

        Category_Box.setBackground(new java.awt.Color(255, 255, 255));
        Category_Box.setForeground(new java.awt.Color(0, 0, 0));
        Category_Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- select --", "Book_Name", "Book_Author", "Code" }));

        Search_Field.setForeground(new java.awt.Color(51, 51, 51));

        SearchBtn.setBackground(new java.awt.Color(255, 255, 255));
        SearchBtn.setForeground(new java.awt.Color(0, 0, 0));
        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        BorrowBook_Table.setBackground(new java.awt.Color(255, 255, 255));
        BorrowBook_Table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BorrowBook_Table.setForeground(new java.awt.Color(0, 0, 0));
        BorrowBook_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "Name", "Author", "Code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BorrowBook_Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(BorrowBook_Table);
        if (BorrowBook_Table.getColumnModel().getColumnCount() > 0) {
            BorrowBook_Table.getColumnModel().getColumn(0).setResizable(false);
            BorrowBook_Table.getColumnModel().getColumn(0).setPreferredWidth(40);
            BorrowBook_Table.getColumnModel().getColumn(1).setMinWidth(0);
            BorrowBook_Table.getColumnModel().getColumn(1).setPreferredWidth(0);
            BorrowBook_Table.getColumnModel().getColumn(1).setMaxWidth(0);
            BorrowBook_Table.getColumnModel().getColumn(2).setPreferredWidth(300);
            BorrowBook_Table.getColumnModel().getColumn(3).setPreferredWidth(240);
            BorrowBook_Table.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        BorrowBtn.setBackground(new java.awt.Color(255, 255, 255));
        BorrowBtn.setForeground(new java.awt.Color(0, 0, 0));
        BorrowBtn.setText("Borrow");
        BorrowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowBtnActionPerformed(evt);
            }
        });

        CancelBtn.setBackground(new java.awt.Color(255, 255, 255));
        CancelBtn.setForeground(new java.awt.Color(0, 0, 0));
        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\aghanaveed_\\Desktop\\JAVA Project\\Library_Managment\\Images\\Borrow_book_icon.png")); // NOI18N
        jLabel6.setText(" Borrow Book");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(Category_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Search_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(BorrowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Category_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BorrowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void BorrowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowBtnActionPerformed
        Borrow_popup borrow2 = new Borrow_popup();
        
        
        ArrayList<Integer> alist = new ArrayList<Integer>();
        String databaseURL = "jdbc:ucanaccess://BookList.accdb";
        try (Connection connection = DriverManager.getConnection(databaseURL)) {

            for (int i=0; i<BorrowBook_Table.getRowCount(); i++) {
                
                if( (boolean)BorrowBook_Table.getValueAt(i, 0) == true ) {
//                    System.out.println(BorrowBook_Table.getValueAt(i, 0));

                    alist.add( (Integer)BorrowBook_Table.getValueAt(i, 1));
                    
                }
             
            }
            
//            this.BorrowBtn.disable();
            
            if(alist.size() == 0) {
                    JOptionPane.showMessageDialog(rootPane, "Select Books first");
            }
            else {
                borrow2.getArrayID(alist);
                borrow2.show();
            }

        } catch (SQLException sq) {
            sq.printStackTrace();
        }
        
    }//GEN-LAST:event_BorrowBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        String CategoryBox = Category_Box.getSelectedItem().toString(), 
               SearchField = Search_Field.getText();
        
        String databaseURL = "jdbc:ucanaccess://BookList.accdb";
        try (Connection connection = DriverManager.getConnection(databaseURL)) {
            String sql;
            
            
            
            if (CategoryBox == "-- select --") {
                sql = "select * from BookList";
            }
            else
                sql = "select * from BookList where "+CategoryBox+"='"+SearchField+"'";
            
            
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            
            ResultSet rs = preparedStatement.executeQuery();
            DefaultTableModel model = (DefaultTableModel) BorrowBook_Table.getModel();

//            Search pr click krne se old wala remove hojaye
//            Delete from bottom to top
            for (int i = model.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);
            }
//            
//          data inserting
            while (rs.next()) {
                    model.addRow(new Object[]{false, rs.getInt("ID"), rs.getString("Book_Name"), rs.getString("Book_Author"),
                    rs.getString("Code")});
                    
            }
            
        } catch (SQLException sq) {
            sq.printStackTrace();
        }
        
//        if (CategoryBox == "-- select --" || SearchField.trim().isEmpty()) {
//            JOptionPane.showMessageDialog(rootPane, "Fill the Blanks", "Warning", JOptionPane.WARNING_MESSAGE);
//        }
    }//GEN-LAST:event_SearchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BorrowBook_Table;
    private javax.swing.JButton BorrowBtn;
    private javax.swing.JButton CancelBtn;
    private javax.swing.JComboBox<String> Category_Box;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField Search_Field;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
